export const projects = [
  {
    id: 0,
    title: 'React',
    subtitle: 'Detailled Portfolio',
    description: 'Portfolio creation process documented',
    image: '',
    link: 'https://github.com/AnneCh/Portfolio_build',
  },
  {
    id: 1,
    title: 'Solidity, JavaScript',
    subtitle: 'NFT MarsKetplace',
    description: 'Creation of an NFT Marketplace',
    image: '/images/mars.png',
    link: 'https://github.com/AnneCh/Portfolio_build',
  },
  {
    id: 2,
    title: 'React',
    subtitle: 'Travel Journal',
    description: 'A simple page displaying mapped objects',
    image: '/images/travels.png',
    link: 'https://travels-journal.vercel.app/',
  },
  {
    id: 3,
    title: 'Solidity, JavaScript',
    subtitle: 'Crypto Bot',
    description: "I'll make it, some day.",
    image: '',
    link: 'https://github.com/AnneCh/Project',
  },
  {
    id: 4,
    title: 'Solidity, Python',
    subtitle: 'TokenFarm Project',
    description: 'Token Farm Lesson with interface',
    image: '/images/staking.png',
    link: 'https://token-farm-tan.vercel.app/',
  },
]

export const topics = [
  {
    id: 0,
    image: '/health.png',
    title: 'Health - Santé',
    description: '',
    link: '/HealthCard_inside',
  },
  {
    id: 1,
    image: '/yinyang.png',
    title: 'Martial Arts - Arts Martiaux',
    description: '',
    link: '/Martial_Inside',
  },
  {
    id: 2,
    image: '/music_notes.png',
    title: 'Music - Musique',
    description: '',
    link: '/Music_Inside',
  },
  // {
  //   image: '',
  //   title: '.',
  //   description: '.',
  //   link: '',
  // },
]

export const tools = [
  'Solidity',
  'Python',
  'JavaScript',
  'Remix',
  'NodeJS',
  'Brownie',
  'Ganache',
  'Infura',
  'Metamask',
  'Linux CLI',
  'HTML',
  'CSS',
  'React',
  'Adobe Audition',
  'Adobe Premiere Pro',
  'Adobe Photoshop',
  'Adobe Indesign',
]
